### ISSUE TITLE
False positives for rule 1007 RemovedClientParameter when using typespec-autorest

### ISSUE THREAD

**Issue by cataggar** [Azure/openapi-diff#280]
Hi, I'm working on https://github.com/Azure/azure-rest-api-specs-pr/pull/15631 and there are a bunch of breaking changes reported for [rule 1007](https://github.com/Azure/openapi-diff/blob/master/docs/rules/1007.md). According to https://github.com/Azure/typespec-azure/issues/3795 , these are false positives. Are these false positives? Can the rule be updated to eliminate these false positives?

How can I suppress these false positives? I've tried a few options with luck:

``` yaml
suppressions:
  - code: RemovedClientParameter
    reason: typespec-autorest puts the parameters in each operation
    from: vmware.json
```

``` yaml
directive:
  - suppress: RemovedClientParameter
    reason: typespec-autorest puts the parameters in each operation
    from: vmware.json
```
